INSERT INTO public.role( id, name)  VALUES (1,'ROLE_ADMIN');
INSERT INTO public.role( id, name)  VALUES (2,'ROLE_INSTRUCTOR');
INSERT INTO public.role( id, name)  VALUES (3,'ROLE_STUDENT');
INSERT INTO public.role( id, name)  VALUES (4,'ROLE_OBSERVER');
INSERT INTO public.role( id, name)  VALUES (5,'ROLE_GUEST');
INSERT INTO public."user"( id, password, username) VALUES (1,'$2a$10$I4X.U473il3rFqFcxl6UruK5TshrlXs/opqLM0hifX5Jelcm4InTG','admin');
INSERT INTO public."user"( id, password, username) VALUES (2,'$2a$10$bRsjrjA9RLw5KLga6NZlouR4K/jK4xrLO6ahPl1SgOMv3dfYof.Ve','instructor');
INSERT INTO public."user"( id, password, username) VALUES (3,'$2a$10$WsPLcPRqMEmhocByrPrq5./ZxBmoqKvtG9WRyKMiRHZ8dR779Uo3O','student');
INSERT INTO public."user"( id, password, username) VALUES (4,'$2a$10$0DjpO.K9ZF61wSGCltEYMuCxw30ayi.hlkyGakjrQNdpboVFv67yG','observer');
INSERT INTO public."user"( id, password, username) VALUES (5,'$2a$10$bsK0W.yFGYivJFw1bYfFL.WjKIF6smUfzmUIgIKjOe7jzGMw8Kb56','guest');
INSERT INTO public.role_to_user(user_id, role_id) VALUES (1, 1);
INSERT INTO public.role_to_user(user_id, role_id) VALUES (2, 2);
INSERT INTO public.role_to_user(user_id, role_id) VALUES (3, 3);
INSERT INTO public.role_to_user(user_id, role_id) VALUES (4, 4);
INSERT INTO public.role_to_user(user_id, role_id) VALUES (5, 5);
